spring.application.name=async-order-system
server.port=8080

# Credenciais CloudAMQP
spring.rabbitmq.addresses=amqp://jaragua-01.lmq.cloudamqp.com
spring.rabbitmq.username=bjnuffmq
spring.rabbitmq.password=gj-YQIiEXyfxQxjsZtiYDKeXIT8ppUq7
spring.rabbitmq.virtual-host=bjnuffmq

# Força o Spring a tentar conectar imediatamente no boot
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s